name: Appium setup

on:
  push:
    branches:
      - main


jobs:
  appium_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 28 ]
        target: [ default ]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.REPO_GIT_TOKEN }}

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'


      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'
          channel: 'stable'

      - run: flutter --version

      - name: Install flutter dependencies
        run: flutter pub get

      - name: Set up NodeJS 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install the Emulator
        run: |
          chmod +x ./scripts/RunAppiumServer.sh
          ./scripts/RunAppiumServer.sh
        shell: bash

      - name: Run Appium Tests
        uses: reactivecircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel 6a
          script: ./gradlew connectedCheck